# action.yaml
name: 'AWS-Cost-Predictor'
description: 'Estimate AWS deployment costs via IAC analysis.'

inputs:
  iac_path:
    description: 'Enter path of the terraform IAC folder'
    required: true
    default: "terraform/"
    
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: | 
        pip install boto3 tabulate
      shell: bash
      
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
      
    - name: Initialize Terraform
      run: terraform init
      working-directory: ${{ inputs.iac_path }}
      shell: bash
      
    - name: Generate tfplan
      run: terraform plan -out=tfplan.binary
      working-directory: ${{ inputs.iac_path }}
      shell: bash
      
    - name: Convert tfplan to JSON
      run: terraform show -json tfplan.binary > tfplan.json
      working-directory: ${{ inputs.iac_path }}
      shell: bash
      
    - name: Pass Inputs to Shell
      run: |
          echo "IAC_PATH=${{ inputs.iac_path }}" >> $GITHUB_ENV
      shell: bash
      
    - name: Download the script
        run: curl -o $PWD/gather_facts.py https://raw.githubusercontent.com/salim8898/AWS-Cost-Predictor/main/code/gather_facts.py
        
    - name: Give script permissions
        run: chmod +x $PWD/gather_facts.py

    - name: Run the AWS cost predict script
      run: python gather_facts.py
      shell: bash
      
branding:
  icon: 'activity'
  color: 'green'
