# action.yaml
name: 'Custom Github Action'
description: 'A Github Action that takes an input and returns the square of the number'

inputs:
  iac_path:
    description: 'Enter path of the terraform IAC folder'
    required: true
    default: "terraform/"
    
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
      
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
      
    - name: Initialize Terraform
      run: terraform init
      working-directory: ${{ inputs.iac_path }}
      shell: bash
      
    - name: Generate tfplan
      run: terraform plan -out=tfplan.binary
      working-directory: ${{ inputs.iac_path }}
      shell: bash
      
    - name: Convert tfplan to JSON
      id: tfplanOutputJson
      run: terraform show -json tfplan.binary > tfplan.json
      working-directory: ${{ inputs.iac_path }}
      shell: bash
      
    - name: Save tfplan JSON file
      run: |
        ls -al
        cat tfplan.json
      working-directory: ${{ inputs.iac_path }}
      shell: bash
      
    - name: Pass Inputs to Shell
      run: |
          echo "IAC_PATH=${{ inputs.iac_path }}" >> $GITHUB_ENV
      shell: bash
      
    - name: Run the AWS cost predict script
      run: python code/gather_facts.py
      shell: bash
