name: AWS Cost Predict
on:
  push:
    branches: [ "main" ]
    
jobs:
  AWS Cost Predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Predict cost
        uses: ./ # Uses an action in the root directory
        # or use a released Github Action
        # uses: repo url
        with:
          iac_path: IAC/
